services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    ports:
      - 80:3000
    restart: unless-stopped
    volumes:
      - ./wakapi-data:/data
    secrets:
      - source: password_salt
        target: password_salt
        uid: '1000'
        gid: '1000'
        mode: '0400'

      - source: db_password
        target: db_password
        uid: '1000'
        gid: '1000'
        mode: '0400'
    environment:
      - WAKAPI_DB_TYPE
      - WAKAPI_DB_NAME
      - WAKAPI_DB_USER
      - WAKAPI_DB_HOST
      - WAKAPI_DB_PORT
      - WAKAPI_DB_PASSWORD
      - WAKAPI_PASSWORD_SALT

secrets:
  password_salt:
    environment: WAKAPI_PASSWORD_SALT
  smtp_pass:
    environment: WAKAPI_MAIL_SMTP_PASS
  db_password:
    environment: WAKAPI_DB_PASSWORD
